// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fbuhtxlcytnnjbrbstmx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZidWh0eGxjeXRubmpicmJzdG14Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzODIzMzEsImV4cCI6MjA1OTk1ODMzMX0.ROFiBdOYpLRTtoNHhsK5krcBbZRT06yIU9zB76-QrX8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);